# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
-
  env:
    - CGO_ENABLED=0

  main:   gen.go
  binary: sqlgen

  # GOOS list to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are darwin and linux.
  goos:
    - darwin
    - linux
    - windows
    - freebsd
#    - netbsd
#    - openbsd
#    - dragonfly

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
    - 386
    - arm
#    - arm64

  # GOARM to build for when GOARCH is arm.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Default is only 6.
  goarm:
    - 6
#    - 7

  # List of combinations of GOOS + GOARCH + GOARM to ignore.
  # Default is empty.
  ignore:
    - goos: darwin
      goarch: 386
    - goos: darwin
      goarch: arm
    - goos: windows
      goarch: 386
    - goos: windows
      goarch: arm

#hooks:
#  post: demo/build.sh

archive:
  replacements:
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
    arm: ARM
    #arm64: ARM64
    darwin: macOS
    openbsd: OpenBSD
    #netbsd: NetBSD
    #freebsd: FreeBSD
    #dragonfly: DragonFlyBSD

  files:
    - LICENSE
    - README.md
    - docs/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^reports:'
