language: go

go:
  - "1.13"

services:
  - mysql
  - postgresql

before_install:
  - mysql -e 'CREATE DATABASE test;'
  - psql -c 'CREATE DATABASE test;' -U postgres

install:
  - unset GOPATH
  - go mod download

script:
  - ./build+test.sh
